apiVersion: apps/v1
kind: Deployment

metadata: 
  name: dev-pro

spec: 
  replicas: 2
  

  selector: 
    matchLabels:
      app: dev-pro


  template: 
    metadata: 
      labels:
        app: dev-pro

    spec: 
      containers:
      - name: dev-pro
        image: karanprajapati/dev-pro:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

  
