---
- name: Deploy application to kubernetes

  hosts: localhost

  tasks:

    - name: Apply Kubernetes Deployment
      command: kubectl apply -f ../k8s/deployment.yaml

    - name: Apply Kubernetes Services
      command: kubectl apply -f ../k8s/service.yaml

    - name: Restart Deployment
      command: kubectl rollout restart deployment/dev-pro



